### PR TITLE
fixed tim's bastardization of this holy bot

### PR DESCRIPTION
**Pull request by mersaults**

### CODE REVIEW

**Comment by WeustiS** [comment]
@s-hfarooq give me perm to allow pulls

**Comment by timot3** [comment]
Queenmoonbot's features are not needed in general, so it just adds to the spam. I thought we were cracking down on it.

**Comment by WeustiS** [comment]
mmm

**Comment by s-hfarooq** [comment]
no, too much spam

if you want to enable a couple commands or some sort of cooldown timer (so that the bot can only be used in general every 5 minutes) do that instead

**Comment by s-hfarooq** [comment]
Bot is now allowed to post some commands in general

**Pull request closed without merging**
